import { useEffect, useMemo, useState } from 'react';
import { Bell, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, FileText, LayoutDashboard, Plus, Search, Settings, SlidersHorizontal, Users, X } from 'lucide-react';

const menu = [{ icon: LayoutDashboard, label: 'Overview' }, { icon: CalendarDays, label: 'Calendar' }, { icon: FileText, label: 'Filings' }, { icon: Users, label: 'Team' }];
const statusClass = { upcoming: 'status-upcoming', overdue: 'status-overdue', completed: 'status-completed' };
const prettyDate = (date) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`));
const initials = (name) => name.split(' ').map((part) => part[0]).join('').slice(0, 2);

function Stat({ label, value, Icon, tone }) { return <article className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20}/></div><div><p>{label}</p><strong>{value}</strong></div></article>; }

function Modal({ close, reload }) {
  const [form, setForm] = useState({ title: '', type: 'GST', dueDate: '', assignee: 'Aditi Sharma', notes: '' });
  const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); setSaving(true); const response = await fetch('/api/filings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (response.ok) { await reload(); close(); } setSaving(false); }
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button className="close" type="button" onClick={close}><X size={20}/></button><p className="eyebrow">NEW COMPLIANCE TASK</p><h2>Add a filing deadline</h2><label>Filing title<input required placeholder="e.g. GSTR-1 · October" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></label><div className="form-row"><label>Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option>GST</option><option>TDS</option><option>Advance Tax</option><option>ROC</option></select></label><label>Due date<input required type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })}/></label></div><label>Assignee<input value={form.assignee} onChange={(event) => setForm({ ...form, assignee: event.target.value })}/></label><label>Notes<textarea rows="3" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })}/></label><button className="primary full" disabled={saving}>{saving ? 'Adding…' : 'Add deadline'} <ChevronRight size={17}/></button></form></div>;
}

function Table({ filings, loading, complete, query, setQuery, compact = false }) {
  const [filter, setFilter] = useState('all');
  const shown = useMemo(() => filings.filter((filing) => (filter === 'all' || filing.status === filter) && `${filing.title} ${filing.type} ${filing.assignee}`.toLowerCase().includes(query.toLowerCase())), [filings, filter, query]);
  return <><div className="table-controls"><div className="filters">{['all', 'upcoming', 'overdue', 'completed'].map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? 'selected' : ''}>{item === 'all' ? 'All filings' : item[0].toUpperCase() + item.slice(1)}</button>)}</div>{!compact && <div className="search"><Search size={18}/><input placeholder="Search filings" value={query} onChange={(event) => setQuery(event.target.value)}/></div>}</div><div className="table-wrap"><table><thead><tr><th>FILING</th><th>DUE DATE</th><th>ASSIGNEE</th><th>STATUS</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="empty">Loading your filings…</td></tr> : shown.length ? shown.map((filing) => <tr key={filing.id}><td><div className="filing-name"><span className={`type-dot ${filing.type.toLowerCase().replace(' ', '-')}`}>{filing.type[0]}</span><div><strong>{filing.title}</strong><small>{filing.notes || filing.type}</small></div></div></td><td>{prettyDate(filing.dueDate)}</td><td><span className="assignee"><b>{initials(filing.assignee)}</b>{filing.assignee}</span></td><td><span className={`status ${statusClass[filing.status]}`}>{filing.status}</span></td><td>{filing.status !== 'completed' && <button className="complete" onClick={() => complete(filing.id)} title="Mark complete"><CheckCircle2 size={19}/></button>}</td></tr>) : <tr><td colSpan="5" className="empty">No filings match this view.</td></tr>}</tbody></table></div></>;
}

function Overview({ dashboard, filings, loading, complete, query, setQuery, navigate }) { return <><header><div><p className="eyebrow">TUESDAY, 7 OCTOBER</p><h1>Good morning, Yash <span>✦</span></h1><p className="subhead">Here’s your business compliance at a glance.</p></div></header><section className="hero"><div><p>UP NEXT</p><h2>{dashboard?.nextDeadline?.title || 'You’re all caught up'}</h2><span><CalendarDays size={16}/>{dashboard?.nextDeadline ? `Due ${prettyDate(dashboard.nextDeadline.dueDate)}` : 'No upcoming deadlines'}</span></div><button className="hero-button" onClick={() => navigate('Filings')}>Review filing <ChevronRight size={17}/></button></section><section className="stats"><Stat label="Total filings" value={dashboard?.summary.total ?? '–'} Icon={FileText} tone="lavender"/><Stat label="Upcoming" value={dashboard?.summary.upcoming ?? '–'} Icon={CalendarDays} tone="blue"/><Stat label="Overdue" value={dashboard?.summary.overdue ?? '–'} Icon={CircleAlert} tone="red"/><Stat label="Completed" value={dashboard?.summary.completed ?? '–'} Icon={CheckCircle2} tone="green"/></section><section className="filings"><div className="section-heading"><div><h2>Priority filings</h2><p>Keep every obligation visible and on track.</p></div><button className="text-button" onClick={() => navigate('Filings')}>View all <ChevronRight size={16}/></button></div><Table filings={filings.slice(0, 5)} loading={loading} complete={complete} query={query} setQuery={setQuery} compact/></section></>; }

function Calendar({ filings, navigate }) { const [month, setMonth] = useState(9); const days = Array.from({ length: 31 }, (_, index) => index + 1); const event = (day) => filings.find((filing) => filing.dueDate === `2026-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`); return <section className="page"><div className="section-heading"><div><p className="eyebrow">COMPLIANCE SCHEDULE</p><h1>Calendar</h1><p>See what needs attention, month by month.</p></div><div className="calendar-controls"><button onClick={() => setMonth(Math.max(0, month - 1))}><ChevronLeft size={18}/></button><strong>{new Date(2026, month).toLocaleString('en-IN', { month: 'long', year: 'numeric' })}</strong><button onClick={() => setMonth(Math.min(11, month + 1))}><ChevronRight size={18}/></button></div></div><div className="calendar-layout"><div className="calendar-card"><div className="weekday-row">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: 3 }, (_, index) => <div className="day-cell muted" key={index}/>)}{days.map((day) => { const filing = event(day); return <div className={`day-cell ${day === 7 && month === 9 ? 'today' : ''}`} key={day}><b>{day}</b>{filing && <button className={`calendar-event ${filing.status}`} onClick={() => navigate('Filings')}>{filing.type}: {filing.title.replace(/^.*·\s*/, '')}</button>}</div>; })}</div></div><aside className="agenda"><p className="eyebrow">THIS MONTH</p><h2>{filings.filter((filing) => filing.dueDate.startsWith(`2026-${String(month + 1).padStart(2, '0')}`)).length} deadlines</h2>{filings.filter((filing) => filing.dueDate.startsWith(`2026-${String(month + 1).padStart(2, '0')}`)).map((filing) => <div className="agenda-item" key={filing.id}><span className={`type-dot ${filing.type.toLowerCase().replace(' ', '-')}`}>{filing.type[0]}</span><div><strong>{filing.title}</strong><small>{prettyDate(filing.dueDate)} · {filing.assignee}</small></div></div>)}</aside></div></section>; }

function Team() { const people = [['Yash Sahu','Owner','purple',2],['Aditi Sharma','Chartered Accountant','orange',3],['Rahul Mehta','Finance Manager','blue',1]]; return <section className="page"><div className="section-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Team & access</h1><p>Manage the people who keep Studio Vertex compliant.</p></div><button className="outline-button"><Plus size={17}/> Invite member</button></div><div className="team-grid">{people.map(([name, role, tone, load]) => <article className="member-card" key={name}><div className={`member-avatar ${tone}`}>{initials(name)}</div><div className="member-title"><div><h2>{name}</h2><span>{role}</span></div><button>•••</button></div><div className="member-meta"><span>Assigned filings</span><b>{load}</b></div><div className="progress"><i style={{ width: `${load * 28}%` }}/></div><small>{load} active filings</small></article>)}</div><div className="activity-card"><div><p className="eyebrow">ACTIVITY</p><h2>Recent workspace updates</h2></div><div className="activity-list"><p><b>Rahul Mehta</b> marked <strong>TDS Return · Q1</strong> as complete <span>2 hours ago</span></p><p><b>Aditi Sharma</b> uploaded a document to <strong>GSTR-3B · September</strong> <span>Yesterday</span></p><p><b>Yash Sahu</b> invited <strong>Rahul Mehta</strong> to the workspace <span>4 Oct</span></p></div></div></section>; }

function SettingsPage() { const [alerts, setAlerts] = useState({ email: true, overdue: true, digest: false }); const choices = [['email','Email deadline alerts','Receive alerts 7, 3, and 1 day before due date.'],['overdue','Overdue escalation','Notify owners when a filing is past due.'],['digest','Weekly digest','Receive a Monday summary of open work.']]; return <section className="page settings-page"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Settings</h1><p>Control company details and notification preferences.</p></div><div className="settings-grid"><form className="settings-card"><h2>Business profile</h2><label>Business name<input defaultValue="Studio Vertex"/></label><label>GSTIN<input defaultValue="27AABCU9603R1ZM"/></label><label>Financial year<select defaultValue="2026-27"><option>2026-27</option><option>2025-26</option></select></label><button type="button" className="primary">Save changes</button></form><section className="settings-card"><h2>Reminder preferences</h2>{choices.map(([key, title, description]) => <div className="toggle-row" key={key}><div><strong>{title}</strong><p>{description}</p></div><button className={`toggle ${alerts[key] ? 'on' : ''}`} onClick={() => setAlerts({...alerts, [key]: !alerts[key]})} type="button"><i/></button></div>)}</section></div></section>; }

export default function App() {
  const [filings, setFilings] = useState([]); const [dashboard, setDashboard] = useState(null); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [page, setPage] = useState('Overview');
  async function load() { setLoading(true); const [filingResponse, dashboardResponse] = await Promise.all([fetch('/api/filings'), fetch('/api/dashboard')]); setFilings(await filingResponse.json()); setDashboard(await dashboardResponse.json()); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function complete(id) { await fetch(`/api/filings/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'completed' }) }); load(); }
  function navigate(next) { setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const content = page === 'Overview' ? <Overview dashboard={dashboard} filings={filings} loading={loading} complete={complete} query={query} setQuery={setQuery} navigate={navigate}/> : page === 'Calendar' ? <Calendar filings={filings} navigate={navigate}/> : page === 'Filings' ? <section className="page"><div className="section-heading"><div><p className="eyebrow">COMPLIANCE REGISTER</p><h1>All filings</h1><p>Search, review, and close every compliance obligation.</p></div><button className="outline-button"><SlidersHorizontal size={17}/> Export report</button></div><div className="insight-strip"><span><CircleAlert size={18}/><b>{filings.filter((filing) => filing.status === 'overdue').length} overdue items</b> need attention before penalties apply.</span><button>View reminders</button></div><Table filings={filings} loading={loading} complete={complete} query={query} setQuery={setQuery}/></section> : page === 'Team' ? <Team/> : <SettingsPage/>;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#top" onClick={() => navigate('Overview')}><span>D</span> DueDate</a><p className="workspace">WORKSPACE</p><div className="company"><div className="avatar">SV</div><div><strong>Studio Vertex</strong><small>Owner workspace</small></div><ChevronRight size={16}/></div><nav>{menu.map(({ icon: Icon, label }) => <button className={page === label ? 'nav-active' : ''} onClick={() => navigate(label)} key={label}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-bottom"><button className={page === 'Settings' ? 'nav-active' : ''} onClick={() => navigate('Settings')}><Settings size={18}/> Settings</button><div className="user"><div className="avatar gradient">YS</div><div><strong>Yash Sahu</strong><small>Owner</small></div></div></div></aside><main id="top"><div className="top-actions"><button className="icon-button"><Bell size={19}/><i/></button><button className="primary" onClick={() => setModal(true)}><Plus size={18}/> Add filing</button></div>{content}</main>{modal && <Modal close={() => setModal(false)} reload={load}/>}</div>;
}
